### ISSUE TITLE
burp插件安装好了，却没有任何选项和ui界面

### ISSUE THREAD

**Issue by dggsec** [x1a0t/Struts2Burp#2]
![image](https://user-images.githubusercontent.com/45778072/111786577-ed557600-88f8-11eb-8087-2cad6e4db2ed.png)
![image](https://user-images.githubusercontent.com/45778072/111786581-ee86a300-88f8-11eb-84e3-7f4141f5270d.png)

您好，请问下burp已经安装了您的插件，为什么在“菜单栏”和“发送至选项”没有显示呢

**Comment by x1a0t** [comment]
你好，插件是被动式扫描的，检测到漏洞就会在taget标签中以issue形式提示，UI目前开发了一点，checkout到dev分支即可
